// <auto-generated />
using System;
using ComprasProgramadas.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComprasProgramadas.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.CestaTopFive", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataAtivacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("cestas_top_five", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.ContaGrafica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("NumeroConta")
                        .IsUnique();

                    b.ToTable("contas_graficas", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.CotacaoHistorica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArquivoOrigem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DataPregao")
                        .HasColumnType("date");

                    b.Property<decimal>("PrecoAbertura")
                        .HasColumnType("decimal(15,6)");

                    b.Property<decimal>("PrecoFechamento")
                        .HasColumnType("decimal(15,6)");

                    b.Property<decimal>("PrecoMaximo")
                        .HasColumnType("decimal(15,6)");

                    b.Property<decimal?>("PrecoMedioDia")
                        .HasColumnType("decimal(15,6)");

                    b.Property<decimal>("PrecoMinimo")
                        .HasColumnType("decimal(15,6)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<decimal?>("VolumeNegociado")
                        .HasColumnType("decimal(20,2)");

                    b.HasKey("Id");

                    b.HasIndex("DataPregao");

                    b.HasIndex("Ticker");

                    b.HasIndex("Ticker", "DataPregao")
                        .IsUnique();

                    b.ToTable("cotacoes_historicas", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.CustodiaFilhote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(15,6)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId");

                    b.HasIndex("ClienteId", "Ticker")
                        .IsUnique();

                    b.ToTable("custodia_filhote", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.CustodiaMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(15,6)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("custodia_master", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.Distribuicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataDistribuicao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("KafkaPublicado")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("OrdemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(15,6)");

                    b.Property<decimal>("ProporcaoCliente")
                        .HasColumnType("decimal(8,6)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("ValorIrDedoDuro")
                        .HasColumnType("decimal(15,6)");

                    b.Property<decimal>("ValorOperacao")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("OrdemId");

                    b.ToTable("distribuicoes", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.EventoIrKafka", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Aliquota")
                        .HasColumnType("decimal(8,6)");

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("LucroLiquido")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("MesReferencia")
                        .HasColumnType("char(7)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Publicado")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ReferenciaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ticker")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorIr")
                        .HasColumnType("decimal(15,6)");

                    b.Property<decimal?>("ValorOperacao")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("eventos_ir_kafka", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.HistoricoValorMensal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorAnterior")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("ValorNovo")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("historico_valor_mensal", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.ItemCesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CestaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CestaId", "Ticker")
                        .IsUnique();

                    b.ToTable("itens_cesta", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.ItemOrdemCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CotacaoFechamento")
                        .HasColumnType("decimal(15,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("OrdemId")
                        .HasColumnType("bigint");

                    b.Property<int>("QtdFracionario")
                        .HasColumnType("int");

                    b.Property<int>("QtdLotePadrao")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeAComprar")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeCalculada")
                        .HasColumnType("int");

                    b.Property<int>("SaldoMasterDescontado")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TickerFracionario")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<decimal>("ValorAlvo")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdemId");

                    b.ToTable("itens_ordem_compra", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.OrdemCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArquivoCotacao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("CestaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DataReferencia")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalConsolidado")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("CestaId");

                    b.ToTable("ordens_compra", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.Rebalanceamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CestaNovaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CestaNovaId");

                    b.ToTable("rebalanceamentos", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.RebalanceamentoCliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataExecucao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("IrDevido")
                        .HasColumnType("decimal(15,2)");

                    b.Property<bool>("KafkaIrPublicado")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("RebalanceamentoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalCompras")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("TotalVendas")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("RebalanceamentoId");

                    b.ToTable("rebalanceamento_clientes", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.VendaMes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Lucro")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("MesReferencia")
                        .IsRequired()
                        .HasColumnType("char(7)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(15,6)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(15,6)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("ValorTotalVenda")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "MesReferencia");

                    b.ToTable("vendas_mes", (string)null);
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.ContaGrafica", b =>
                {
                    b.HasOne("ComprasProgramadas.Domain.Entities.Cliente", "Cliente")
                        .WithOne("ContaGrafica")
                        .HasForeignKey("ComprasProgramadas.Domain.Entities.ContaGrafica", "ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.CustodiaFilhote", b =>
                {
                    b.HasOne("ComprasProgramadas.Domain.Entities.Cliente", "Cliente")
                        .WithMany("CustodiasFilhote")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasProgramadas.Domain.Entities.ContaGrafica", "ContaGrafica")
                        .WithMany("CustodiasFilhote")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.Distribuicao", b =>
                {
                    b.HasOne("ComprasProgramadas.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasProgramadas.Domain.Entities.OrdemCompra", "Ordem")
                        .WithMany()
                        .HasForeignKey("OrdemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Ordem");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.EventoIrKafka", b =>
                {
                    b.HasOne("ComprasProgramadas.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.HistoricoValorMensal", b =>
                {
                    b.HasOne("ComprasProgramadas.Domain.Entities.Cliente", "Cliente")
                        .WithMany("HistoricoValorMensal")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.ItemCesta", b =>
                {
                    b.HasOne("ComprasProgramadas.Domain.Entities.CestaTopFive", "Cesta")
                        .WithMany("Itens")
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cesta");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.ItemOrdemCompra", b =>
                {
                    b.HasOne("ComprasProgramadas.Domain.Entities.OrdemCompra", "Ordem")
                        .WithMany("Itens")
                        .HasForeignKey("OrdemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordem");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.OrdemCompra", b =>
                {
                    b.HasOne("ComprasProgramadas.Domain.Entities.CestaTopFive", "Cesta")
                        .WithMany()
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cesta");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.Rebalanceamento", b =>
                {
                    b.HasOne("ComprasProgramadas.Domain.Entities.CestaTopFive", "CestaNova")
                        .WithMany()
                        .HasForeignKey("CestaNovaId");

                    b.Navigation("CestaNova");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.RebalanceamentoCliente", b =>
                {
                    b.HasOne("ComprasProgramadas.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasProgramadas.Domain.Entities.Rebalanceamento", "Rebalanceamento")
                        .WithMany("Clientes")
                        .HasForeignKey("RebalanceamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Rebalanceamento");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.VendaMes", b =>
                {
                    b.HasOne("ComprasProgramadas.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.CestaTopFive", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ContaGrafica");

                    b.Navigation("CustodiasFilhote");

                    b.Navigation("HistoricoValorMensal");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.ContaGrafica", b =>
                {
                    b.Navigation("CustodiasFilhote");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.OrdemCompra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ComprasProgramadas.Domain.Entities.Rebalanceamento", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
